version: "3.7"

services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
    flask:
        build:
            context: ${PWD}
            dockerfile: ./web/Dockerfile
        container_name: flask
        restart: always
        environment:
            APPLICATION_DB: ${APPLICATION_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        expose:
            - 8080
        volumes:
            - ${PWD}:/opt/code
        depends_on:
                - db

    nginx:
        image: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 80:80
        depends_on:
            - web
volumes:
    pgdata: